name: Reproduce and verify packages

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - '**'
  schedule:
    # Hourly schedule.
    #
    #        ┌───────────── minute           (0 - 59)
    #        │  ┌────────── hour             (0 - 23)
    #        │  │  ┌─────── day of the month (1 - 31)
    #        │  │  │  ┌──── month            (1 - 12 or JAN-DEC)
    #        │  │  │  │  ┌─ day of the week  (0 - 6 or SUN-SAT)
    #        │  │  │  │  │
    #        │  │  │  │  │
    #        │  │  │  │  │
    - cron: '0  *  *  *  *'

permissions:
  contents: read

jobs:
  reproduce:
    name: "Reproduce ${{ matrix.tag }}"
    strategy:
      matrix:
        tag:
          - '6.6.2'
          - '6.5.5'
        source:
          - develop.svn.wordpress.org
          - develop.git.wordpress.org
          - github-wordpress-develop
          - core.trac.wordpress.org
      fail-fast: false
    uses: ./.github/workflows/reproduce.yml
    with:
      tag: ${{ matrix.tag }}
      source: ${{ matrix.source }}
  compare:
    name: "Compare ${{ matrix.tag }}"
    needs:
      - reproduce
    strategy:
      matrix:
        tag:
          - '6.6.2'
          - '6.5.5'
        source:
          - develop.git.wordpress.org
          - github-wordpress-develop
          - core.trac.wordpress.org
      fail-fast: false
    uses: ./.github/workflows/compare.yml
    with:
      tag: ${{ matrix.tag }}
      source: ${{ matrix.source }}
  verify:
    name: "Verify ${{ matrix.tag }}"
    needs:
      - reproduce
    strategy:
      matrix:
        tag:
          - '6.6.2'
          - '6.5.5'
        package:
          - wordpress.org-zip
          - wordpress.org-tar
          - downloads.wordpress.org-zip
          - downloads.wordpress.org-tar
          - build.trac.wordpress.org
          - github-zip
          - github-tar
          - roots-wordpress-full
          - johnpbloch-wordpress
      fail-fast: false
    uses: ./.github/workflows/verify.yml
    with:
      tag: ${{ matrix.tag }}
      package: ${{ matrix.package }}
  test-zip-hashes:
    name: "Test zip hashes / ${{ matrix.tag }}"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        tag:
          - '6.6.2'
          - '6.5.5'
      fail-fast: false
    steps:
      - name: Download zip and hashes from wordpress.org
        run: |
          wget -O package.zip "https://wordpress.org/wordpress-${{ matrix.tag }}.zip"
          wget -O package.zip.md5 "https://wordpress.org/wordpress-${{ matrix.tag }}.zip.md5"
          wget -O package.zip.sha1 "https://wordpress.org/wordpress-${{ matrix.tag }}.zip.sha1"

      - name: Check the md5 hash
        run: |
          echo "$(cat package.zip.md5) package.zip" | md5sum -c -

      - name: Check the sha1 hash
        run: |
          echo "$(cat package.zip.sha1) package.zip" | sha1sum -c -
  test-tar-hashes:
    name: "Test tar hashes / ${{ matrix.tag }}"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        tag:
          - '6.6.2'
          - '6.5.5'
      fail-fast: false
    steps:
      - name: Download tar.gz and hashes from wordpress.org
        run: |
          wget -O package.tar.gz "https://wordpress.org/wordpress-${{ matrix.tag }}.tar.gz"
          wget -O package.tar.gz.md5 "https://wordpress.org/wordpress-${{ matrix.tag }}.tar.gz.md5"
          wget -O package.tar.gz.sha1 "https://wordpress.org/wordpress-${{ matrix.tag }}.tar.gz.sha1"

      - name: Check the md5 hash
        run: |
          echo "$(cat package.tar.gz.md5) package.tar.gz" | md5sum -c -

      - name: Check the sha1 hash
        run: |
          echo "$(cat package.tar.gz.sha1) package.tar.gz" | sha1sum -c -
